name: dotnet build

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: user-auth/GraphTutorial/
      run: dotnet restore
    - name: Build
      working-directory: user-auth/GraphTutorial/
      run: dotnet build --no-restore
    - name: Restore dependencies
      working-directory: app-auth/GraphAppOnlyTutorial/
      run: dotnet restore
    - name: Build
      working-directory: app-auth/GraphAppOnlyTutorial/
      run: dotnet build --no-restore
